# Generated by Django 4.0.1 on 2022-05-01 13:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomIntroducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('imageone', models.ImageField(upload_to='classimage')),
            ],
            options={
                'verbose_name': '教室借用情形',
                'verbose_name_plural': '教室借用情形',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='課程名稱')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='課程內容')),
                ('type', models.CharField(choices=[('1', '專業'), ('2', '核心'), ('3', '微學分課程及工作坊')], max_length=1)),
                ('image', models.ImageField(upload_to='courseimage', verbose_name='封面圖')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
            },
        ),
        migrations.CreateModel(
            name='DownLoadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('1', '專業領域小組'), ('2', '課程'), ('3', '設備及物品借用'), ('4', 'TA實習申請')], max_length=1, null=True)),
                ('content', models.TextField(verbose_name='說明')),
                ('filepath', models.FileField(upload_to='uploads')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '相關辦法',
                'verbose_name_plural': '相關辦法',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='設備內文')),
                ('number', models.TextField(blank=True, null=True, verbose_name='數量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '設備介紹',
                'verbose_name_plural': '設備介紹',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='標題')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('type', models.CharField(choices=[('1', '智慧製造'), ('2', '資訊通'), ('3', '機器人'), ('4', '創課'), ('5', '元宇宙')], max_length=1, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '專業領域小組',
                'verbose_name_plural': '專業領域小組',
            },
        ),
        migrations.CreateModel(
            name='Memebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('extension', models.CharField(max_length=20, verbose_name='分機')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='電子信箱')),
                ('work', models.TextField(verbose_name='業務職掌')),
                ('location', models.TextField(verbose_name='位置')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '成員',
                'verbose_name_plural': '成員',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='標題')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='編輯器內文')),
                ('type', models.CharField(choices=[('1', '最新消息'), ('2', '學生活動'), ('3', '學術動態')], max_length=1)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '最新公告',
                'verbose_name_plural': '最新公告',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='教室代碼')),
                ('name', models.CharField(max_length=30, verbose_name='教室名稱')),
                ('space_description', models.TextField(verbose_name='空間介紹')),
                ('number', models.CharField(max_length=30, verbose_name='容納人數')),
                ('equipment_description', models.CharField(max_length=30, verbose_name='設備資訊')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '空間介紹',
                'verbose_name_plural': '空間介紹',
            },
        ),
    ]
