# Generated by Django 4.0.1 on 2022-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': '最新公告', 'verbose_name_plural': '最新公告'},
        ),
        migrations.AddField(
            model_name='memebers',
            name='image',
            field=models.ImageField(null=True, upload_to='membersimage'),
        ),
    ]
