# Generated by Django 4.0.1 on 2022-02-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classroomintroduct',
            new_name='classroomintroducts',
        ),
    ]
