# Generated by Django 4.0.1 on 2022-02-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_rename_classroomintroduct_classroomintroducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomintroducts',
            name='imageone',
            field=models.ImageField(default='', upload_to='classimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadfiles',
            name='filepath',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
