# Generated by Django 4.0.1 on 2022-02-23 05:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('1', '智慧製造'), ('2', '資訊通'), ('3', '機器人'), ('4', '創課'), ('5', '元宇宙')], max_length=1)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
            ],
        ),
        migrations.CreateModel(
            name='Memebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('extension', models.IntegerField(max_length=30, verbose_name='分機')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='電子信箱')),
                ('work', models.TextField(verbose_name='業務職掌')),
                ('location', models.TextField(verbose_name='位置')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='教室代碼')),
                ('name', models.CharField(max_length=30, verbose_name='教室名稱')),
                ('space_description', models.TextField(verbose_name='空間介紹')),
                ('number', models.CharField(max_length=30, verbose_name='容納人數')),
                ('equipment_description', models.CharField(max_length=30, verbose_name='設備資訊')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '最新公告', 'verbose_name_plural': '最新公告'},
        ),
        migrations.AlterField(
            model_name='classroomintroducts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='coures',
            name='content',
            field=models.TextField(verbose_name='課程內容'),
        ),
        migrations.AlterField(
            model_name='coures',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='coures',
            name='title',
            field=models.CharField(max_length=30, verbose_name='課程名稱'),
        ),
        migrations.AlterField(
            model_name='downloadfiles',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='編輯器內文'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30, verbose_name='標題'),
        ),
    ]
