# Generated by Django 4.0.1 on 2022-02-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_group_memebers_space_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memebers',
            name='extension',
            field=models.IntegerField(verbose_name='分機'),
        ),
    ]
