# Generated by Django 4.0.1 on 2022-02-23 08:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0008_alter_memebers_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomintroducts',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='coures',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='downloadfiles',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='memebers',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='classroomintroducts',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='coures',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='downloadfiles',
            name='type',
            field=models.CharField(choices=[('1', '專業領域小組'), ('2', '課程'), ('3', '設備及物品借用'), ('4', 'TA實習申請')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='downloadfiles',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='標題'),
        ),
        migrations.AddField(
            model_name='group',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='memebers',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('1', '專業實作課程'), ('2', '核心實作課程'), ('3', '微學分課程及工作坊')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='space',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='coures',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='課程內容'),
        ),
        migrations.AlterField(
            model_name='coures',
            name='type',
            field=models.CharField(choices=[('1', '專業實作課程'), ('2', '核心實作課程'), ('3', '微學分課程及工作坊')], max_length=1),
        ),
        migrations.AlterField(
            model_name='downloadfiles',
            name='content',
            field=models.TextField(verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='group',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', '智慧製造'), ('2', '資訊通'), ('3', '機器人'), ('4', '創課'), ('5', '元宇宙')], max_length=1, null=True),
        ),
    ]
