# Generated by Django 4.0.1 on 2022-02-24 05:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_rename_date_classroomintroducts_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='課程名稱')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='課程內容')),
                ('type', models.CharField(choices=[('1', '專業實作課程'), ('2', '核心實作課程'), ('3', '微學分課程及工作坊')], max_length=1)),
                ('image', models.ImageField(upload_to='courseimage', verbose_name='封面圖')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='設備名稱')),
                ('description', models.TextField(verbose_name='設備介紹')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.DeleteModel(
            name='Coures',
        ),
    ]
