# Generated by Django 4.0.1 on 2022-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0010_course_equipment_delete_coures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('1', '專業'), ('2', '核心'), ('3', '微學分課程及工作坊')], max_length=1),
        ),
        migrations.AlterField(
            model_name='space',
            name='equipment_description',
            field=models.TextField(verbose_name='設備資訊'),
        ),
    ]
