# Generated by Django 4.0.1 on 2022-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0010_course_equipment_delete_coures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomintroducts',
            options={'verbose_name': '空間介紹', 'verbose_name_plural': '空間介紹'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '課程', 'verbose_name_plural': '課程'},
        ),
        migrations.AlterModelOptions(
            name='downloadfiles',
            options={'verbose_name': '相關辦法', 'verbose_name_plural': '相關辦法'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '設備介紹', 'verbose_name_plural': '設備介紹'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '專業領域小組', 'verbose_name_plural': '專業領域小組'},
        ),
        migrations.AlterModelOptions(
            name='memebers',
            options={'verbose_name': '成員', 'verbose_name_plural': '成員'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': '空間介紹', 'verbose_name_plural': '空間介紹'},
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('1', '專業'), ('2', '核心'), ('3', '微學分課程及工作坊')], max_length=1),
        ),
    ]
