# Generated by Django 4.0.1 on 2022-03-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0011_alter_classroomintroducts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomintroducts',
            options={'verbose_name': '教室借用情形', 'verbose_name_plural': '教室借用情形'},
        ),
        migrations.AlterField(
            model_name='memebers',
            name='extension',
            field=models.CharField(max_length=20, verbose_name='分機'),
        ),
    ]
