# Generated by Django 4.0.1 on 2022-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_alter_classroomintroducts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomintroducts',
            options={'verbose_name': '教室借用情形', 'verbose_name_plural': '教室借用情形'},
        ),
    ]
