# Generated by Django 4.0.1 on 2022-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_alter_classroomintroducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='typeshow',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('1', '最新消息'), ('2', '學生活動'), ('3', '學術動態')], max_length=1),
        ),
    ]
