# Generated by Django 4.0.1 on 2022-04-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0011_alter_course_type_alter_space_equipment_description'),
        ('BackEnd', '0013_alter_classroomintroducts_options'),
        ('BackEnd', '0014_remove_course_typeshow'),
    ]

    operations = [
    ]
