# Generated by Django 4.0.1 on 2022-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0015_merge_20220427_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(null=True, upload_to='equipmentimage'),
        ),
        migrations.AlterField(
            model_name='space',
            name='code',
            field=models.CharField(max_length=8, verbose_name='教室代碼'),
        ),
        migrations.AlterField(
            model_name='space',
            name='equipment_description',
            field=models.CharField(max_length=30, verbose_name='設備資訊'),
        ),
    ]
